name: Build

on:
  push:
    branches: [master, production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - run: |
        npm ci
        npm run build

      - name: Archive build artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
