name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master, production]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      # TODO: use DEPLOY_DEST from env
      DEPLOY_DEST: ${{secrets.DEPLOY_DEST}}

    steps:
      - uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - run: |
        set -eu
        mkdir "$HOME/.ssh"
        echo "${{secrets.SSH_KEY}}" > "$HOME/.ssh/id_rsa"
        chmod 600 "$HOME/.ssh/id_rsa"

      - run: sh scripts/deploy/deploy.sh
