name: Build and Deploy

on:
  push:
    branches: [master, production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies and build the project
        run: |
          npm ci
          npm run build

      - name: Upload client build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build/client
          path: .tmp/build/client

      - name: Upload server build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build/server
          path: .tmp/build/server

  deploy_development:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: development
    needs: build

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      DEPLOY_DEST: ${{secrets.DEPLOY_DEST}}

    steps:
      - uses: actions/checkout@v2
      - name: Download client build artifact
        uses: actions/download-artifact@v2
        with:
          name: build/client
          path: .tmp/build/client

      - uses: actions/checkout@v2
      - name: Download server build artifact
        uses: actions/download-artifact@v2
        with:
          name: build/server
          path: .tmp/build/server

      - name: Setup SSH
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "$SSH_KEY" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

      - run: sh scripts/deploy/deploy.sh

  deploy_production:
    if: ${{ github.ref == 'refs/heads/production' }}
    runs-on: ubuntu-latest
    environment: production
    needs: build

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      DEPLOY_DEST: ${{secrets.DEPLOY_DEST}}

    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Setup SSH
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "$SSH_KEY" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

      - run: sh scripts/deploy/deploy.sh
