name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{secrets.SSH_KEY}}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"

      - run: npm ci
      - run: npm run build

      - run: sh deploy/upload.sh
