name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{secrets.SSH_KEY}}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"

      - run: npm ci
      - run: npm run build

      - name: Archive "dist" directory
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      DEPLOY_DEST: ${{secrets.DEPLOY_DEST}}

    steps:
      - uses: actions/checkout@v2
      - name: Download "dist" directory
        uses: actions/download-artifact@v2
        with:
          name: dist

      - run: sh scripts/deploy/deploy.sh
